### ISSUE TITLE
Polygons support

### ISSUE THREAD

**Issue by targence** [lab0x0/szmakermap#15]
```
{
  "type": "Polygon",
  "coordinates": [
    [
      [-104.05, 48.99],
      [-97.22, 48.98],
      [-96.58, 45.94],
      [-104.03, 45.94],
      [-104.05, 48.99]
    ]
  ]
}

```

**Comment by clemsos** [comment]
For now, we only support Point type

https://github.com/lab0x0/szmakermap/blob/34637c70bf4239175474a68aaa8251aa80ce8aa2/index.html#L43

As soon as we have a data sample for polygon in `list.json` I can add support for Polygon

**Comment by clemsos** [comment]
Maybe we can add one specific mall in Huaqiangbei as a test?

**Comment by targence** [comment]
Ok, I will add sample in this weekend

**Comment by targence** [comment]
feedback ：）

![screen shot 2017-10-18 at 3 48 39 pm](https://user-images.githubusercontent.com/415928/31719464-40bbb2b0-b41c-11e7-90d6-67f636d1313c.png)


1. need infill polygon half transparent color.
2. point pin not needed in this case
3. pop up will be show up after clicking on polygon

**Comment by clemsos** [comment]
originally, I added a marker because it was easier to notice. Zones do not appear clearly while zoom is further. 

See the green zone next to the marker - if you don't know it is here, you'll miss it. 

![screenshot](https://user-images.githubusercontent.com/743246/31958272-7a7ad47a-b8f1-11e7-822d-ba919f7df601.jpeg)

One way will be to hide marker when zoom is close and show it while zoom is out.

**Comment by targence** [comment]
is it possible to show pop up when I click to polygon?

**Comment by targence** [comment]
![screen shot 2017-10-25 at 8 40 17 am](https://user-images.githubusercontent.com/415928/31982458-a725d068-b961-11e7-97fc-4a8b0715f468.png)
